include:
  - project: 'Bigouden/gitlab-ci-templates'
    file: '.gitlab-ci-docker.yml'
    
stages:
  - Quality
  - Build
  - Commands
  - Collections
  - Python Modules
  - Inspect
  - Release

default:
  image: $CONTAINER_TEST_IMAGE

Ansible:
  stage: Commands
  script:
    - ansible --version
  variables:
    GIT_STRATEGY: none

Ansible Galaxy: 
  stage: Commands
  script:
    - ansible-galaxy --version
  variables:
    GIT_STRATEGY: none

Ansible Lint: 
  stage: Commands
  script:
    - ansible-lint --version
  variables:
    GIT_STRATEGY: none

Ansible Playbook: 
  stage: Commands
  script:
    - ansible-playbook --version
  variables:
    GIT_STRATEGY: none

Ansible Vault: 
  stage: Commands
  script:
    - ansible-vault --version
  variables:
    GIT_STRATEGY: none

Git CLI:
  stage: Commands
  extends: .standalone
  script:
    - git version

Netcommon: 
  stage: Collections
  script:
    - ansible-galaxy collection list | grep ansible.netcommon
  variables:
    GIT_STRATEGY: none

Posix: 
  stage: Collections
  script:
    - ansible-galaxy collection list | grep ansible.posix
  variables:
    GIT_STRATEGY: none

Crypto: 
  stage: Collections
  script:
    - ansible-galaxy collection list | grep community.crypto
  variables:
    GIT_STRATEGY: none

General: 
  stage: Collections
  script:
    - ansible-galaxy collection list | grep community.general
  variables:
    GIT_STRATEGY: none

Kubernetes: 
  stage: Collections
  script:
    - ansible-galaxy collection list | grep community.kubernetes
  variables:
    GIT_STRATEGY: none

Cloud: 
  stage: Collections
  script:
    - ansible-galaxy collection list | grep google.cloud
  variables:
    GIT_STRATEGY: none

Docker: 
  stage: Collections
  extends: .standalone
  script:
    - ansible-galaxy collection list | grep community.docker

Postgresql: 
  stage: Collections
  extends: .standalone
  script:
    - ansible-galaxy collection list | grep community.postgresql

Mongodb: 
  stage: Collections
  extends: .standalone
  script:
    - ansible-galaxy collection list | grep community.mongodb

Bcrypt:
  stage: Python Modules
  extends: .standalone
  script:
    - python3 -c "import sys, pkgutil; sys.exit(0 if pkgutil.find_loader('bcrypt') else 1)"

Git:
  stage: Python Modules
  extends: .standalone
  script:
    - python3 -c "import sys, pkgutil; sys.exit(0 if pkgutil.find_loader('git') else 1)"

Passlib:
  stage: Python Modules
  script:
    - python3 -c "import sys, pkgutil; sys.exit(0 if pkgutil.find_loader('passlib') else 1)"
