include:
  - project: 'Bigouden/gitlab-ci-templates'
    file: '.gitlab-ci-docker.yml'
    
stages:
  - Quality
  - Build
  - Commands
  - Collections
  - Python Modules
  - Inspect
  - Release

default:
  image: $CONTAINER_TEST_IMAGE

Ansible:
  stage: Commands
  script:
    - ansible --version
  variables:
    GIT_STRATEGY: none

Ansible Galaxy: 
  stage: Commands
  script:
    - ansible-galaxy --version
  variables:
    GIT_STRATEGY: none

Ansible Lint: 
  stage: Commands
  script:
    - ansible-lint --version
  variables:
    GIT_STRATEGY: none

Ansible Playbook: 
  stage: Commands
  script:
    - ansible-playbook --version
  variables:
    GIT_STRATEGY: none

Ansible Vault: 
  stage: Commands
  script:
    - ansible-vault --version
  variables:
    GIT_STRATEGY: none

Netcommon: 
  stage: Collections
  script:
    - ansible-galaxy collection list | grep ansible.netcommon
  variables:
    GIT_STRATEGY: none

Posix: 
  stage: Collections
  script:
    - ansible-galaxy collection list | grep ansible.posix
  variables:
    GIT_STRATEGY: none

Crypto: 
  stage: Collections
  script:
    - ansible-galaxy collection list | grep community.crypto
  variables:
    GIT_STRATEGY: none

General: 
  stage: Collections
  script:
    - ansible-galaxy collection list | grep community.general
  variables:
    GIT_STRATEGY: none

Kubernetes: 
  stage: Collections
  script:
    - ansible-galaxy collection list | grep community.kubernetes
  variables:
    GIT_STRATEGY: none

Cloud: 
  stage: Collections
  script:
    - ansible-galaxy collection list | grep google.cloud
  variables:
    GIT_STRATEGY: none

Bcrypt:
  stage: Python Modules
  script:
    - python3 -c "import sys, pkgutil; sys.exit(0 if pkgutil.find_loader('bcrypt') else 1)"

Passlib:
  stage: Python Modules
  script:
    - python3 -c "import sys, pkgutil; sys.exit(0 if pkgutil.find_loader('passlib') else 1)"

DockerHub (PRO):
  stage: Release
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $DOCKER_HUB_ENTERPRISE_USER -p $DOCKER_HUB_ENTERPRISE_PASSWORD
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $DOCKER_HUB_VERSION_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $DOCKER_HUB_LATEST_IMAGE
    - docker push $DOCKER_HUB_VERSION_IMAGE
    - docker push $DOCKER_HUB_LATEST_IMAGE
  inherit:
    default: false
  variables:
    DOCKER_HUB_VERSION_IMAGE: $DOCKER_HUB_ENTERPRISE_USER/ansible:$CI_COMMIT_REF_NAME
    DOCKER_HUB_LATEST_IMAGE: $DOCKER_HUB_ENTERPRISE_USER/ansible:latest
    GIT_STRATEGY: none
  rules:
    - if: $DOCKER_HUB_ENTERPRISE_USER && $DOCKER_HUB_ENTERPRISE_PASSWORD
      when: manual
