image: docker:latest
services:
  - docker:dind

stages:
  - Build
  - Test
  - Release
  
include:
  template: Container-Scanning.gitlab-ci.yml

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

Build:
  stage: Build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

Test Ansible:
  stage: Test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE
  variables:
    GIT_STRATEGY: none

Test Ansible Lint: 
  stage: Test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run  $CONTAINER_TEST_IMAGE ansible-lint --version
  variables:
    GIT_STRATEGY: none

Test Ansible Playbook: 
  stage: Test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run  $CONTAINER_TEST_IMAGE ansible-playbook --version
  variables:
    GIT_STRATEGY: none

Test Ansible Vault: 
  stage: Test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run  $CONTAINER_TEST_IMAGE ansible-vault --version
  variables:
    GIT_STRATEGY: none


Release Image:
  stage: Release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  variables:
    GIT_STRATEGY: none
  only:
    - master
