include:
  - project: 'Bigouden/gitlab-ci-templates'
    file: '.gitlab-ci-docker.yml'
    
stages:
  - Quality
  - Build
  - Test
  - Inspect
  - Release

variables:
  GIT_STRATEGY: none

default:
  image: $CONTAINER_TEST_IMAGE

Ansible:
  stage: Test
  script:
    - ansible --version

Ansible Lint: 
  stage: Test
  script:
    - ansible-lint --version

Ansible Playbook: 
  stage: Test
  script:
    - ansible-playbook --version

Ansible Vault: 
  stage: Test
    - ansible-vault --version

DockerHub (PRO):
  stage: Release
  before_script:
    - docker login -u $DOCKER_HUB_ENTERPRISE_USER -p $DOCKER_HUB_ENTERPRISE_PASSWORD
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $DOCKER_HUB_VERSION_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $DOCKER_HUB_LATEST_IMAGE
    - docker push $DOCKER_HUB_VERSION_IMAGE
    - docker push $DOCKER_HUB_LATEST_IMAGE
  variables:
    DOCKER_HUB_VERSION_IMAGE: $DOCKER_HUB_ENTERPRISE_USER/ansible:$CI_COMMIT_REF_NAME
    DOCKER_HUB_LATEST_IMAGE: $DOCKER_HUB_ENTERPRISE_USER/ansible:latest
  inherit:
    default: false
  rules:
    - if: $DOCKER_HUB_ENTERPRISE_USER && $DOCKER_HUB_ENTERPRISE_PASSWORD
      when: manual
