workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID

image: docker:latest
services:
  - docker:dind

stages:
  - Quality
  - Build
  - Test
  - Release
  
variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:test
  CONTAINER_VERSION_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  CONTAINER_LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  DOCKER_HUB_VERSION_IMAGE: dnum/ansible:$CI_COMMIT_REF_NAME
  DOCKER_HUB_LATEST_IMAGE: dnum/ansible:latest

Hadolint:
  stage: Quality
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint --ignore DL3013 --ignore DL3018 Dockerfile

Build:
  stage: Build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

Test Ansible:
  stage: Test
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE
  variables:
    GIT_STRATEGY: none

Test Ansible Lint: 
  stage: Test
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run  $CONTAINER_TEST_IMAGE ansible-lint --version
  variables:
    GIT_STRATEGY: none

Test Ansible Playbook: 
  stage: Test
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run  $CONTAINER_TEST_IMAGE ansible-playbook --version
  variables:
    GIT_STRATEGY: none

Test Ansible Vault: 
  stage: Test
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run  $CONTAINER_TEST_IMAGE ansible-vault --version
  variables:
    GIT_STRATEGY: none

Release:
  stage: Release
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_VERSION_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $DOCKER_HUB_VERSION_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_LATEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $DOCKER_HUB_LATEST_IMAGE
    - docker push $CONTAINER_VERSION_IMAGE
    - docker push $DOCKER_HUB_VERSION_IMAGE
    - docker push $CONTAINER_LATEST_IMAGE
    - docker push $DOCKER_HUB_LATEST_IMAGE
  variables:
    GIT_STRATEGY: none
  when: manual